import type { OfficialSource } from "./sourceTypes";

export const OFFICIAL_AI_SOURCES: OfficialSource[] = [
  {
    id: "openai",
    company: "OpenAI",
    products: ["ChatGPT", "GPT-4", "GPT-4.1", "OpenAI API"],
    website: "https://openai.com/news",
    // OpenAI publishes an official News RSS
    rss: "https://openai.com/news/rss.xml",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "MODEL_RELEASE", "API_UPDATE"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "google-ai",
    company: "Google AI",
    products: ["Gemini", "Imagen", "Veo"],
    website: "https://blog.google/technology/ai/",
    rss: "https://blog.google/technology/ai/rss/",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "MODEL_RELEASE", "RESEARCH"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "deepmind",
    company: "DeepMind",
    products: ["Gemini", "AlphaFold"],
    website: "https://deepmind.google/discover/blog/",
    rss: "https://deepmind.google/blog/rss.xml",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["MODEL_RELEASE", "RESEARCH"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "anthropic",
    company: "Anthropic",
    products: ["Claude"],
    website: "https://www.anthropic.com/news",
    // No official RSS available; placeholder for future custom feed
    rss: undefined,
    fetchMethod: "LISTING_PAGE",
    listingUrl: "https://www.anthropic.com/news",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "MODEL_RELEASE", "API_UPDATE"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "microsoft-ai",
    company: "Microsoft",
    products: ["Copilot", "Azure AI"],
    website: "https://www.microsoft.com/ai/blog",
    rss: "https://blogs.microsoft.com/ai/feed/",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "API_UPDATE"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "meta-ai",
    company: "Meta AI",
    products: ["LLaMA", "Meta AI"],
    website: "https://ai.meta.com/",
    // No official AI RSS; use engineering as an official Meta feed that includes AI/ML stories
    rss: "https://engineering.fb.com/feed/",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["MODEL_RELEASE", "RESEARCH"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "meta-newsroom",
    company: "Meta Newsroom",
    products: ["Meta", "Meta AI", "LLaMA"],
    website: "https://about.fb.com/news/",
    rss: "https://about.fb.com/news/feed/",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "MODEL_RELEASE", "RESEARCH", "GENERAL"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "nvidia",
    company: "NVIDIA",
    products: ["GPUs", "CUDA", "AI Stack"],
    website: "https://blogs.nvidia.com/blog/category/artificial-intelligence/",
    rss: "https://blogs.nvidia.com/feed/",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "RESEARCH", "GENERAL"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "perplexity",
    company: "Perplexity",
    products: ["Perplexity Search", "Pages"],
    website: "https://blog.perplexity.ai/",
    // No reliable RSS; treat Perplexity as a discovery engine, not a primary source
    rss: undefined,
    fetchMethod: "NONE",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE"],
    sourceType: "AGGREGATOR",
  },
  {
    id: "huggingface",
    company: "Hugging Face",
    products: ["Models", "Spaces", "Datasets"],
    website: "https://huggingface.co/blog",
    rss: "https://huggingface.co/blog/feed.xml",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["MODEL_RELEASE", "RESEARCH"],
    sourceType: "OFFICIAL_BLOG",
  },
  // ---- TECH / RESEARCH NEWS (old RSS feeds, lower priority via TECH_NEWS / RESEARCH_LAB) ----
  {
    id: "microsoft-research",
    company: "Microsoft Research",
    products: ["AI Research"],
    website: "https://www.microsoft.com/en-us/research/",
    rss: "https://www.microsoft.com/en-us/research/feed/",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["RESEARCH"],
    sourceType: "RESEARCH_LAB",
  },
  {
    id: "the-gradient",
    company: "The Gradient",
    products: ["AI Research"],
    website: "https://thegradient.pub/",
    rss: "https://thegradient.pub/rss/",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["RESEARCH"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "kdnuggets",
    company: "KDnuggets",
    products: ["Data Science", "ML"],
    website: "https://www.kdnuggets.com/",
    rss: "https://www.kdnuggets.com/feed",
    fetchMethod: "RSS",
    trust: "MEDIUM",
    contentTypes: ["RESEARCH", "GENERAL"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "mit-tech-review",
    company: "MIT Technology Review",
    products: ["Tech News"],
    website: "https://www.technologyreview.com/",
    rss: "https://www.technologyreview.com/feed/",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["RESEARCH", "GENERAL"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "wired",
    company: "Wired",
    products: ["Tech News"],
    website: "https://www.wired.com/",
    rss: "https://www.wired.com/feed/rss",
    fetchMethod: "RSS",
    trust: "MEDIUM",
    contentTypes: ["GENERAL"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "ars-technica",
    company: "Ars Technica",
    products: ["Tech News"],
    website: "https://arstechnica.com/",
    rss: "http://feeds.arstechnica.com/arstechnica/index/",
    fetchMethod: "RSS",
    trust: "MEDIUM",
    contentTypes: ["GENERAL"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "techcrunch-ai",
    company: "TechCrunch AI",
    products: ["AI News"],
    website: "https://techcrunch.com/tag/ai/",
    rss: "https://techcrunch.com/tag/ai/feed/",
    fetchMethod: "RSS",
    trust: "MEDIUM",
    contentTypes: ["GENERAL"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "venturebeat-ai",
    company: "VentureBeat AI",
    products: ["AI News"],
    website: "https://venturebeat.com/category/ai/",
    rss: "https://venturebeat.com/category/ai/feed/",
    fetchMethod: "RSS",
    trust: "MEDIUM",
    contentTypes: ["GENERAL"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "the-verge",
    company: "The Verge",
    products: ["Tech News"],
    website: "https://www.theverge.com/",
    rss: "https://www.theverge.com/rss/index.xml",
    fetchMethod: "RSS",
    trust: "MEDIUM",
    contentTypes: ["GENERAL"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "engadget",
    company: "Engadget",
    products: ["Tech News"],
    website: "https://www.engadget.com/",
    rss: "https://www.engadget.com/rss.xml",
    fetchMethod: "RSS",
    trust: "MEDIUM",
    contentTypes: ["GENERAL"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "gizmodo",
    company: "Gizmodo",
    products: ["Tech News"],
    website: "https://gizmodo.com/",
    rss: "https://gizmodo.com/rss",
    fetchMethod: "RSS",
    trust: "MEDIUM",
    contentTypes: ["GENERAL"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "techradar",
    company: "TechRadar",
    products: ["Tech News"],
    website: "https://www.techradar.com/",
    rss: "https://www.techradar.com/rss",
    fetchMethod: "RSS",
    trust: "MEDIUM",
    contentTypes: ["GENERAL"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "zdnet",
    company: "ZDNet",
    products: ["Tech News"],
    website: "https://www.zdnet.com/",
    rss: "https://www.zdnet.com/news/rss.xml",
    fetchMethod: "RSS",
    trust: "MEDIUM",
    contentTypes: ["GENERAL"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "xai",
    company: "xAI",
    products: ["Grok"],
    website: "https://x.ai/blog",
    fetchMethod: "LISTING_PAGE",
    listingUrl: "https://x.ai/blog",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "MODEL_RELEASE", "RESEARCH"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "mistral",
    company: "Mistral",
    products: ["Mistral models"],
    website: "https://mistral.ai/news",
    fetchMethod: "LISTING_PAGE",
    listingUrl: "https://mistral.ai/news",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "MODEL_RELEASE", "RESEARCH"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "cohere",
    company: "Cohere",
    products: ["Cohere models", "Command"],
    website: "https://cohere.com/blog",
    fetchMethod: "LISTING_PAGE",
    listingUrl: "https://cohere.com/blog",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "MODEL_RELEASE", "API_UPDATE", "RESEARCH"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "stability-ai",
    company: "Stability AI",
    products: ["Stable Diffusion"],
    website: "https://stability.ai/blog",
    fetchMethod: "LISTING_PAGE",
    listingUrl: "https://stability.ai/blog",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "MODEL_RELEASE", "RESEARCH"],
    sourceType: "OFFICIAL_BLOG",
  },
];

