import type { OfficialSource } from "./sourceTypes";

/**
 * Official + high-quality AI sources registry.
 * - company: used as article.source display name
 * - fetchMethod: RSS vs listing-page discovery
 * - trust/sourceType: used downstream for filtering rules
 */
export const OFFICIAL_AI_SOURCES: OfficialSource[] = [
  // Tier 1: Official AI companies / labs
  {
    id: "openai",
    company: "OpenAI",
    products: ["ChatGPT", "OpenAI API", "GPT"],
    website: "https://openai.com/news",
    rss: "https://openai.com/news/rss.xml",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "MODEL_RELEASE", "API_UPDATE"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "anthropic",
    company: "Anthropic",
    products: ["Claude"],
    website: "https://www.anthropic.com/news",
    fetchMethod: "LISTING_PAGE",
    listingUrl: "https://www.anthropic.com/news",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "MODEL_RELEASE", "API_UPDATE", "RESEARCH"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "xai",
    company: "xAI",
    products: ["Grok"],
    website: "https://x.ai",
    fetchMethod: "LISTING_PAGE",
    listingUrl: "https://x.ai/news",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "MODEL_RELEASE", "API_UPDATE"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "google-ai",
    company: "Google AI",
    products: ["Gemini", "Vertex AI"],
    website: "https://blog.google/technology/ai/",
    rss: "https://blog.google/technology/ai/rss/",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "MODEL_RELEASE", "RESEARCH"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "deepmind",
    company: "DeepMind",
    products: ["Gemini", "AlphaFold"],
    website: "https://deepmind.google/discover/blog",
    fetchMethod: "LISTING_PAGE",
    listingUrl: "https://deepmind.google/discover/blog/",
    trust: "HIGH",
    contentTypes: ["RESEARCH", "MODEL_RELEASE"],
    sourceType: "RESEARCH_LAB",
  },
  {
    id: "meta-ai",
    company: "Meta AI",
    products: ["Llama"],
    website: "https://ai.meta.com/blog/",
    fetchMethod: "LISTING_PAGE",
    listingUrl: "https://ai.meta.com/blog/",
    trust: "HIGH",
    contentTypes: ["MODEL_RELEASE", "RESEARCH", "PRODUCT_UPDATE"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "microsoft-ai",
    company: "Microsoft AI",
    products: ["Copilot", "Azure AI"],
    website: "https://www.microsoft.com/ai/blog",
    rss: "https://www.microsoft.com/en-us/ai/blog/feed/",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "MODEL_RELEASE", "API_UPDATE"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "microsoft-research",
    company: "Microsoft Research",
    products: ["Research"],
    website: "https://www.microsoft.com/en-us/research",
    rss: "https://www.microsoft.com/en-us/research/feed/",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["RESEARCH"],
    sourceType: "RESEARCH_LAB",
  },
  {
    id: "nvidia",
    company: "NVIDIA AI",
    products: ["CUDA", "TensorRT", "NIM", "DGX"],
    website: "https://blogs.nvidia.com",
    rss: "https://blogs.nvidia.com/feed/",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "MODEL_RELEASE", "RESEARCH", "NEWS"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "huggingface",
    company: "Hugging Face",
    products: ["Transformers", "Spaces"],
    website: "https://huggingface.co/blog",
    rss: "https://huggingface.co/blog/feed.xml",
    fetchMethod: "RSS",
    trust: "HIGH",
    contentTypes: ["PRODUCT_UPDATE", "MODEL_RELEASE", "RESEARCH"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "mistral",
    company: "Mistral",
    products: ["Mistral models"],
    website: "https://mistral.ai",
    fetchMethod: "LISTING_PAGE",
    listingUrl: "https://mistral.ai/news/",
    trust: "HIGH",
    contentTypes: ["MODEL_RELEASE", "PRODUCT_UPDATE", "API_UPDATE"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "cohere",
    company: "Cohere",
    products: ["Command", "Embed"],
    website: "https://cohere.com",
    fetchMethod: "LISTING_PAGE",
    listingUrl: "https://cohere.com/blog",
    trust: "HIGH",
    contentTypes: ["MODEL_RELEASE", "PRODUCT_UPDATE", "API_UPDATE"],
    sourceType: "OFFICIAL_BLOG",
  },
  {
    id: "stability",
    company: "Stability AI",
    products: ["Stable Diffusion"],
    website: "https://stability.ai",
    fetchMethod: "LISTING_PAGE",
    listingUrl: "https://stability.ai/blog",
    trust: "HIGH",
    contentTypes: ["MODEL_RELEASE", "PRODUCT_UPDATE"],
    sourceType: "OFFICIAL_BLOG",
  },

  // Tier 2: High-quality tech / AI journalism and research outlets (lower trust/priority)
  {
    id: "mit-tech-review",
    company: "MIT Tech Review",
    products: [],
    website: "https://www.technologyreview.com",
    rss: "https://www.technologyreview.com/feed/",
    fetchMethod: "RSS",
    trust: "MEDIUM",
    contentTypes: ["NEWS", "RESEARCH"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "wired",
    company: "Wired",
    products: [],
    website: "https://www.wired.com",
    rss: "https://www.wired.com/feed/rss",
    fetchMethod: "RSS",
    trust: "MEDIUM",
    contentTypes: ["NEWS"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "ars-technica",
    company: "Ars Technica",
    products: [],
    website: "https://arstechnica.com",
    rss: "http://feeds.arstechnica.com/arstechnica/index/",
    fetchMethod: "RSS",
    trust: "MEDIUM",
    contentTypes: ["NEWS"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "techcrunch-ai",
    company: "TechCrunch AI",
    products: [],
    website: "https://techcrunch.com/tag/ai/",
    rss: "https://techcrunch.com/tag/ai/feed/",
    fetchMethod: "RSS",
    trust: "LOW",
    contentTypes: ["NEWS"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "venturebeat-ai",
    company: "VentureBeat AI",
    products: [],
    website: "https://venturebeat.com/category/ai/",
    rss: "https://venturebeat.com/category/ai/feed/",
    fetchMethod: "RSS",
    trust: "LOW",
    contentTypes: ["NEWS"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "the-gradient",
    company: "The Gradient",
    products: [],
    website: "https://thegradient.pub",
    rss: "https://thegradient.pub/rss/",
    fetchMethod: "RSS",
    trust: "MEDIUM",
    contentTypes: ["RESEARCH"],
    sourceType: "RESEARCH_LAB",
  },
  {
    id: "kdnuggets",
    company: "KDnuggets",
    products: [],
    website: "https://www.kdnuggets.com",
    rss: "https://www.kdnuggets.com/feed",
    fetchMethod: "RSS",
    trust: "LOW",
    contentTypes: ["NEWS", "OTHER"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "techradar",
    company: "TechRadar",
    products: [],
    website: "https://www.techradar.com",
    rss: "https://www.techradar.com/rss",
    fetchMethod: "RSS",
    trust: "LOW",
    contentTypes: ["NEWS"],
    sourceType: "TECH_NEWS",
  },
  {
    id: "zdnet",
    company: "ZDNet",
    products: [],
    website: "https://www.zdnet.com",
    rss: "https://www.zdnet.com/news/rss.xml",
    fetchMethod: "RSS",
    trust: "LOW",
    contentTypes: ["NEWS"],
    sourceType: "TECH_NEWS",
  },
];

